import Header from '@/app/components/layout/Header'
import './globals.css'

export const metadata = {
  title: 'PanaverseDao',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        </body>
    </html>
  )
}
